##test.yml
name: Test Workflow firstworkflow
on:
    # Trigger 1: On code pushes to specific branches
  push: 
    branches:
      - 'main'
  workflow_dispatch: # Trigger 2: Manual trigger from GitHub Actions UI
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: downloading code from second-action-react-demo repo
        uses: actions/checkout@v3
        #with:
        #  repository: second-action-react-demo
        #  token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci 
      - name: Run tests
        run: npm test 
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: downloading code from second-action-react-demo repo
        uses: actions/checkout@v3
        #with:
        #  repository: second-action-react-demo ##
        #  token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: echo "Installing dependencies..." && npm ci
      - name: Build the project
        run: echo "Building the project..." && npm run build